/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.ControleCliente;
import javax.swing.JOptionPane;

/**
 *
 * @author aluno
 */
public class JPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JPrincipal
     */
    public JPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        btFecharComanda = new javax.swing.JButton();
        btAdicionarItem = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        cadastro = new javax.swing.JMenu();
        cadClientes = new javax.swing.JMenuItem();
        cadComandas = new javax.swing.JMenuItem();
        cadItens = new javax.swing.JMenuItem();
        cadMesa = new javax.swing.JMenuItem();
        consultas = new javax.swing.JMenu();
        conClientes = new javax.swing.JMenuItem();
        conComandas = new javax.swing.JMenuItem();
        conItens = new javax.swing.JMenuItem();
        conMesas = new javax.swing.JMenuItem();
        conReservas = new javax.swing.JMenuItem();
        relatorios = new javax.swing.JMenu();
        relClientes = new javax.swing.JMenuItem();
        descontos = new javax.swing.JMenu();
        desVisitas = new javax.swing.JMenuItem();
        desGastos = new javax.swing.JMenuItem();
        desAniversario = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Restaurante");

        btFecharComanda.setText("Fechar Comanda");
        btFecharComanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFecharComandaActionPerformed(evt);
            }
        });

        btAdicionarItem.setText("Adicionar Itens em uma Comanda");
        btAdicionarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarItemActionPerformed(evt);
            }
        });

        cadastro.setText("Cadastro");

        cadClientes.setText("Clientes");
        cadClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadClientesActionPerformed(evt);
            }
        });
        cadastro.add(cadClientes);

        cadComandas.setText("Comandas");
        cadComandas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadComandasActionPerformed(evt);
            }
        });
        cadastro.add(cadComandas);

        cadItens.setText("Itens");
        cadItens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadItensActionPerformed(evt);
            }
        });
        cadastro.add(cadItens);

        cadMesa.setText("Mesa");
        cadMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadMesaActionPerformed(evt);
            }
        });
        cadastro.add(cadMesa);

        jMenuBar1.add(cadastro);

        consultas.setText("Consultas");

        conClientes.setText("Clientes");
        conClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conClientesActionPerformed(evt);
            }
        });
        consultas.add(conClientes);

        conComandas.setText("Comandas");
        conComandas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conComandasActionPerformed(evt);
            }
        });
        consultas.add(conComandas);

        conItens.setText("Itens");
        conItens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conItensActionPerformed(evt);
            }
        });
        consultas.add(conItens);

        conMesas.setText("Mesas");
        conMesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conMesasActionPerformed(evt);
            }
        });
        consultas.add(conMesas);

        conReservas.setText("Reservas");
        conReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conReservasActionPerformed(evt);
            }
        });
        consultas.add(conReservas);

        jMenuBar1.add(consultas);

        relatorios.setText("Relatórios");

        relClientes.setText("Clientes");
        relClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relClientesActionPerformed(evt);
            }
        });
        relatorios.add(relClientes);

        jMenuBar1.add(relatorios);

        descontos.setText("Descontos");

        desVisitas.setText("Visitas");
        desVisitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desVisitasActionPerformed(evt);
            }
        });
        descontos.add(desVisitas);

        desGastos.setText("Gastos");
        desGastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desGastosActionPerformed(evt);
            }
        });
        descontos.add(desGastos);

        desAniversario.setText("Aniversário");
        desAniversario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desAniversarioActionPerformed(evt);
            }
        });
        descontos.add(desAniversario);

        jMenuBar1.add(descontos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btFecharComanda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btAdicionarItem, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btFecharComanda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAdicionarItem)
                .addContainerGap(203, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cadComandasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadComandasActionPerformed
        CadComandas cadastroComandas = new CadComandas(this, true);
        cadastroComandas.setVisible(true);
    }//GEN-LAST:event_cadComandasActionPerformed

    private void cadClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadClientesActionPerformed
        CadClientes cadCliente = new CadClientes(this, true);
        cadCliente.setVisible(true);
    }//GEN-LAST:event_cadClientesActionPerformed

    private void cadItensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadItensActionPerformed
        CadItens cadastroItens = new CadItens(this, true);
        cadastroItens.setVisible(true);
    }//GEN-LAST:event_cadItensActionPerformed

    private void cadMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadMesaActionPerformed
        CadMesas cadastroMesa = new CadMesas(this, true);
        cadastroMesa.setVisible(true);
    }//GEN-LAST:event_cadMesaActionPerformed

    private void conClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conClientesActionPerformed
        ConClientes consultaClientes = new ConClientes(this, true);
        consultaClientes.setVisible(true);
    }//GEN-LAST:event_conClientesActionPerformed

    private void btFecharComandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFecharComandaActionPerformed
        FecharComanda fecharComanda = new FecharComanda(this, true);
        fecharComanda.setVisible(true);
    }//GEN-LAST:event_btFecharComandaActionPerformed

    private void btAdicionarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarItemActionPerformed
        CadItemComanda cadItemComanda = new CadItemComanda(this, true);
        cadItemComanda.setVisible(true);
    }//GEN-LAST:event_btAdicionarItemActionPerformed

    private void conComandasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conComandasActionPerformed
        ConComandas consultaComandas = new ConComandas(this, true);
        consultaComandas.setVisible(true);
    }//GEN-LAST:event_conComandasActionPerformed

    private void conItensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conItensActionPerformed
        ConItens consultaItens = new ConItens(this, true);
        consultaItens.setVisible(true);
    }//GEN-LAST:event_conItensActionPerformed

    private void conMesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conMesasActionPerformed
        ConMesas consultaMesas = new ConMesas(this, true);
        consultaMesas.setVisible(true);
    }//GEN-LAST:event_conMesasActionPerformed

    private void conReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conReservasActionPerformed
        ConReserva conReserva = new ConReserva(this, true);
        conReserva.setVisible(true);
    }//GEN-LAST:event_conReservasActionPerformed

    private void relClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relClientesActionPerformed
        if (controleCliente.geraRelatorio()) {
            JOptionPane.showMessageDialog(this, "Relatório construído com sucesso! c: (gerado no diretório '/home/aluno/')");
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao gerar realatório :c");
        }
    }//GEN-LAST:event_relClientesActionPerformed

    private void desVisitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desVisitasActionPerformed
        EdicaoDesVisitas edicaoVisitas = new EdicaoDesVisitas(this, true);
        edicaoVisitas.setVisible(true);
    }//GEN-LAST:event_desVisitasActionPerformed

    private void desGastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desGastosActionPerformed
        EdicaoDesGastos edicaoGastos = new EdicaoDesGastos(this, true);
        edicaoGastos.setVisible(true);
    }//GEN-LAST:event_desGastosActionPerformed

    private void desAniversarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desAniversarioActionPerformed
        EdicaoDesAniversario edicaoAniversario = new EdicaoDesAniversario(this, true);
        edicaoAniversario.setVisible(true);
    }//GEN-LAST:event_desAniversarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JPrincipal().setVisible(true);
            }
        });
    }

    private ControleCliente controleCliente = ControleCliente.getInstancia();
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdicionarItem;
    private javax.swing.JButton btFecharComanda;
    private javax.swing.JMenuItem cadClientes;
    private javax.swing.JMenuItem cadComandas;
    private javax.swing.JMenuItem cadItens;
    private javax.swing.JMenuItem cadMesa;
    private javax.swing.JMenu cadastro;
    private javax.swing.JMenuItem conClientes;
    private javax.swing.JMenuItem conComandas;
    private javax.swing.JMenuItem conItens;
    private javax.swing.JMenuItem conMesas;
    private javax.swing.JMenuItem conReservas;
    private javax.swing.JMenu consultas;
    private javax.swing.JMenuItem desAniversario;
    private javax.swing.JMenuItem desGastos;
    private javax.swing.JMenuItem desVisitas;
    private javax.swing.JMenu descontos;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem relClientes;
    private javax.swing.JMenu relatorios;
    // End of variables declaration//GEN-END:variables
}
